Social Media App milestone 2
Leon-Mbegera/ror-social-scaffold pull request #2
Opened 2021-07-12 10:56 UTC by Leon-Mbegera

2021-07-12 11:39 UTC, mke2111 requested changes
# STATUS: CHANGES REQUIRED 🔴 ♻️ 

## Hey Happy Coder, 👋🏽 
**This is a great project you have going on, well-done lad**. 

### Well-done 💯 
    1. The app runs just fine

**However, there are a few sections to improve before your project is approved.** 🔴 
<hr>

### REQUIRED

- [x] Add a PR description explaining all the implemented features in this milestone.
- [x] The testing command in the readme file should be `rspec` and not `rpsec`.
- [ ] Add unit and integration tests for your app. [Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/tests.png)
- [ ] A logged-in user is able to send themselves a friend request. This should not be the expected app's behaviour. Give this a quick fix.
- [ ] Posts timeline includes posts written by logged-in user and their friends ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png) from Pathwright)
- [ ] After sending a request from the single user page, the send request button is still visible and a request can be sent numerous times, Remove the button and clear up this issue.
- [ ] Accepting a friend request is currently not successful. Give this issue a quick look into it.
- [ ] Check the inline comments below for more sections to improve

#

### Kindly make all the requested changes and submit another CRR. 💯 

**Cheers 🍹 and Happy coding 💻** 

<hr>

Mention @mke2111 in this thread and I'll be glad to help. 😄 
### Best regards
Slack 🆘  Roy Mukuye
Twitter 🐦  [Roy Mukuye](https://twitter.com/Roymkenya)
LinkedIn 🔗  [Roy Mukuye](https://www.linkedin.com/in/roy-mukuye/)

2021-07-12 11:43 UTC, mke2111 commented on app/models/user.rb
> +  has_many :pending_friends, through: :pending_friendships, source: :friend_id
- [ ] Remove these two lines of SQL queries. They'll come in handy in the next milestone. The ruby enumerables will do the job perfectly for now.

2021-07-12 11:43 UTC, mke2111 commented on app/models/user.rb
> +  has_many :friends, through: :accepted_friendships, source: :friend_id
- [ ] Remove these two lines of SQL queries. They'll come in handy in the next milestone. The ruby enumerables will do the job perfectly for now.

2021-07-12 11:43 UTC, mke2111 commented on app/models/user.rb
> +  has_many :friend_requests, through: :inverse_friendships, source: :user_id
- [ ] Remove these two lines of SQL queries. They'll come in handy in the next milestone. The ruby enumerables will do the job perfectly for now.

2021-07-15 16:20 UTC, elisha2kyakpo1 requested changes
# STATUS: CHANGES REQUIRED 🔴 ♻️
Hey, @Leon-Mbegera you have done really good, this is impressive. From the last reviewer's comments, I have seen that some changes are not being addressed.

## To highlight

- You have added tests, which is good.
- The pr has descriptive comments.
- A user can send a request for friendship.

1. The app runs just fine
However, there are a few sections to improve before your project is approved. 🔴

REQUIRED
 

- [ ] Posts timeline includes posts written by logged-in user and their friends. Currently, every logged-in user can see a post from every user, even from users who are not friends.
- [ ]  There is a repeat of friend requests, which in turn created a duplicate friendship. See from the image below:
![repeat](https://user-images.githubusercontent.com/53124548/125822452-ef09bd2b-a653-4e93-b3f1-4347046871c6.png)
![repeat1](https://user-images.githubusercontent.com/53124548/125822461-7d3da216-0a11-44c3-87dd-52ddc2ad6aed.png)

**Kindly make all the requested changes and submit another CRR. 💯**
Cheers 🍹 and Happy coding 💻

<hr>
In case you have a question, just mention **elisha2kyakpo1**, and I will respond.

2021-07-15 18:09 UTC, SajjadAhmad14 requested changes
# Changes Required :recycle:
> "Change is inevitable. Change is constant. -Benjamin Disraeli"
## Hello, you have been doing a tremendous job so far :ok_hand:
## To Highlight 🎉
- [ ] Git flow is used properly.
- [ ] README includes instructions to run the project locally.
## To Improve 🙏
- [ ] User should be able to accept friendship requests to start a friendship. Please see this [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png).
- [ ] User can reject a friendship request. Please see this [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png).
- [ ] Posts timeline should be of posts written by logged-in user and their friends. Please see this [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png).
# Optional
- [ ] Views should be completely separate from app logic. You can move all view-related logic to app/helpers.
### Happy Coding ☺️
## If you have any questions you can comment here in this PR or can always connect with me on slack ( @Sajjad Ahmad ).

2021-07-15 19:27 UTC, SajjadAhmad14 requested changes
# Changes Required :recycle:
> "Change is inevitable. Change is constant. -Benjamin Disraeli"
## Hello, you have been doing a tremendous job so far :ok_hand:
## To Improve 🙏
- [ ] User should be able to accept friendship requests to start a friendship. Please see this [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png).
- [ ] User can reject a friendship request. Please see this [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png).
- [ ] Posts timeline should be of posts written by logged-in user and their friends. Please see this [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png).
# Optional
- [ ] Views should be completely separate from app logic. You can move all view-related logic to app/helpers.
### Happy Coding ☺️
## If you have any questions you can comment here in this PR or can always connect with me on slack ( @Sajjad Ahmad ).

2021-07-15 20:21 UTC, SajjadAhmad14 approved these changes
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:
## Congratulations 🎉 Thank you for implementing changes suggested previously 🙏
### Happy Coding ☺️
## If you have any questions you can comment here in this PR or can always connect with me on slack ( @Sajjad Ahmad ).

2021-07-16 08:31 UTC, merged